#!/usr/bin/env python3
"""Generate inline data for top menu toggle lists."""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, List

REPO_ROOT = Path(__file__).resolve().parents[1]

BOOKS = [
    {
        "name": "1AM1100",
        "root": REPO_ROOT / "local/restored/1AM1100/S1",
        "output": "js/sectionMenuData.js",
    },
    {
        "name": "1AM2100",
        "root": REPO_ROOT / "local/restored/1AM2100/S2",
        "output": "js/sectionMenuData.js",
    },
]

ANCHOR_RE = re.compile(r'<a\s+[^>]*href="([^\"]+)"[^>]*>(.*?)</a>', re.IGNORECASE | re.DOTALL)
TAG_RE = re.compile(r'<[^>]+>')
SPACE_RE = re.compile(r'\s+')
DATA_PAGE_RE = re.compile(r'data-page="([^\"]+)"', re.IGNORECASE)


def clean_text(value: str) -> str:
    value = value.replace('&nbsp;', ' ')
    text = TAG_RE.sub('', value)
    text = SPACE_RE.sub(' ', text).strip()
    return text


def normalize_href(menu_file: Path, href: str, book_root: Path) -> str:
    if href.startswith('http://') or href.startswith('https://'):
        return href
    parts = href.split('#', 1)
    rel_path = parts[0]
    anchor = parts[1] if len(parts) == 2 else ''
    target_path = (menu_file.parent / rel_path).resolve()
    try:
        relative_path = target_path.relative_to(book_root)
    except ValueError:
        relative_path = target_path
    href_path = relative_path.as_posix()
    if anchor:
        return f"{href_path}#{anchor}"
    return href_path


def extract_links(menu_file: Path, book_root: Path) -> List[Dict[str, str]]:
    html = menu_file.read_text(encoding='utf-8')
    links: List[Dict[str, str]] = []
    for match in ANCHOR_RE.finditer(html):
        href = match.group(1).strip()
        body = match.group(2)
        text = clean_text(body)
        if not href or not text:
            continue
        data_page_match = DATA_PAGE_RE.search(match.group(0))
        data_page = data_page_match.group(1).strip() if data_page_match else ''
        normalized_href = normalize_href(menu_file, href, book_root)
        links.append({
            "href": normalized_href,
            "text": text,
            "page": data_page,
        })
    return links


def build_data(book: Dict[str, Path]) -> Dict[str, List[Dict[str, str]]]:
    menu_dir = book["root"] / "menu"
    result: Dict[str, List[Dict[str, str]]] = {}
    for html_file in sorted(menu_dir.glob('*.html')):
        rel_key = f"menu/{html_file.name}"
        result[rel_key] = extract_links(html_file, book["root"])
    return result


def write_js(data: Dict[str, List[Dict[str, str]]], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open('w', encoding='utf-8') as fh:
        fh.write('// Auto-generated by generate_section_menu_data.py. Do not edit manually.\n')
        json_data = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
        fh.write(f"window.__SECTION_MENU_DATA = {json_data};\n")


def main() -> None:
    for book in BOOKS:
        data = build_data(book)
        output_path = book["root"] / book["output"]
        write_js(data, output_path)
        rel_out = output_path.relative_to(REPO_ROOT)
        print(f"[info] wrote {rel_out}")


if __name__ == '__main__':
    main()
